import type { Character } from "~/api";

export const TEST_CHARACTERS: Character[] = [
  {
    name: "Test Character A",
    url: "a",
    mass: "",
    films: [],
    edited: "",
    gender: "male",
    height: "",
    created: "",
    species: [],
    vehicles: [],
    eye_color: "",
    homeworld: "",
    starships: [],
    birth_year: "",
    hair_color: "",
    skin_color: "",
  },
  {
    name: "Test Character B",
    url: "b",
    mass: "",
    films: [],
    edited: "",
    gender: "female",
    height: "",
    created: "",
    species: [],
    vehicles: [],
    eye_color: "",
    homeworld: "",
    starships: [],
    birth_year: "",
    hair_color: "",
    skin_color: "",
  },
];
